[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://portfolio-software-tester.netlify.app"

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
